name: Validate

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/library-validate.yml
    secrets:
      codecov-token: ${{secrets.CODECOV_TOKEN}}
    with:
      go-version: ${{vars.GO_VERSION}}
      go-versions: ${{vars.GO_VERSIONS}}
      golangci-lint-version: ${{vars.GOLANGCI_LINT_VERSION}}
      platforms: ${{vars.PLATFORMS}}
